#!/usr/bin/ruby

require 'optparse'
require 'aws-sdk'

require_relative 'directory_streamer'

banner = "Usage: s3reamer DIRECTORY BUCKET_NAME [options]"
if ARGV.length < 2
  $stderr.puts banner
  exit 1
end

dir = ARGV.shift
if !File.exists?(dir)
  $stderr.puts "Directory does not exist: #{dir}"
  exit 1
elsif !File.directory?(dir)
  $stderr.puts "Not a directory: #{dir}"
  exit 1
end

bucket_name = ARGV.shift

options = {
  region: 'us-east-1',
  bucket_name: bucket_name,
  directory: dir
}
OptionParser.new do |opts|
  opts.banner =

  opts.on("-r", "--region [AWS_REGION]") do |v|
    options[:region] = v
  end
end

credentials = Aws::Credentials.new(ENV['AWS_ACCESS_TOKEN_ID'], ENV['AWS_SECRET_ACCESS_KEY'])
s3 = Aws::S3::Resource.new(region: options[:region], credentials: c)
bucket = s3.bucket(options[:bucket_name])
watcher = S3reamer::DirectoryStreamer.new(options[:directory], bucket)
watcher.run
